#!/usr/bin/env python3
"""
scrape-inav-timers.py -- Extract timer-to-pad mappings from INAV target.c files.

Reads DEF_TIM() entries from each board's target.c and extracts:
  - Pad label (S1, S2, etc. from comment)
  - Hardware timer number (TIM1 = 1, TIM8 = 8, etc.)
  - Default usage (OUTPUT_AUTO, LED, BEEPER, etc.)

Output: TypeScript data file for use in inavImport.ts

Usage:
    python3 tools/scrape-inav-timers.py --inav-src /path/to/inav/src/main/target
    python3 tools/scrape-inav-timers.py --inav-src /tmp/inav-fw/src/main/target --output src/models/inavTimerData.ts
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path


def parse_target_c(filepath: str) -> list[dict] | None:
    """Parse a target.c file and extract DEF_TIM entries."""
    try:
        with open(filepath, 'r') as f:
            content = f.read()
    except Exception:
        return None

    entries = []
    # Match DEF_TIM(TIMn, CHx, PINxx, TIM_USE_xxx, ...) // comment
    pattern = re.compile(
        r'DEF_TIM\(\s*TIM(\d+)\s*,'   # timer number
        r'\s*CH\w+\s*,'                # channel (ignored)
        r'\s*P\w+\s*,'                 # pin (ignored)
        r'\s*TIM_USE_(\w+)'            # usage flags
        r'.*?\)'                        # rest of macro
        r'[^/]*//(.*?)$',             # trailing comment
        re.MULTILINE
    )

    for match in pattern.finditer(content):
        timer_num = int(match.group(1))
        usage = match.group(2).strip()
        comment = match.group(3).strip()

        # Extract pad label from comment (S1, S2, LED, BEEPER, etc.)
        pad_match = re.match(r'(S\d+)', comment)
        pad_label = pad_match.group(1) if pad_match else None

        # Determine if this is an output pin, LED, beeper, or other
        is_output = usage in ('OUTPUT_AUTO', 'MC_MOTOR', 'MC_SERVO',
                              'FW_MOTOR', 'FW_SERVO', 'ANY')
        is_led = 'LED' in usage
        is_beeper = 'BEEPER' in usage

        entries.append({
            'timerNum': timer_num,
            'padLabel': pad_label,
            'usage': usage,
            'isOutput': is_output,
            'isLed': is_led,
            'isBeeper': is_beeper,
            'comment': comment,
        })

    return entries if entries else None


def extract_board_name(target_dir: str) -> str:
    """Get board name from directory name."""
    return os.path.basename(target_dir)


def generate_typescript(boards: dict, output_path: str):
    """Generate TypeScript data file."""
    lines = [
        '/**',
        ' * inavTimerData.ts -- Timer-to-pad mappings for INAV boards.',
        ' *',
        ' * Auto-generated by tools/scrape-inav-timers.py from INAV firmware target.c files.',
        ' * DO NOT EDIT MANUALLY.',
        ' *',
        f' * Generated from {len(boards)} boards.',
        ' */',
        '',
        'export interface InavTimerPin {',
        '  /** Hardware timer number (TIM1=1, TIM8=8, etc.) */',
        '  timerNum: number;',
        '  /** Physical pad label (S1, S2, etc.) or null for non-output pins */',
        '  padLabel: string | null;',
        '  /** Default usage from target.c */',
        '  usage: string;',
        '  /** Is this an output pin (motor/servo capable) */',
        '  isOutput: boolean;',
        '  /** Is this a LED pin */',
        '  isLed: boolean;',
        '  /** Is this a beeper pin */',
        '  isBeeper: boolean;',
        '}',
        '',
        '/**',
        ' * Map of INAV board name -> array of timer pin definitions.',
        ' * Array order matches the timerHardware[] array in the firmware.',
        ' *',
        ' * Usage: given timer_output_mode N = MODE, look up TIM(N+1) in this table',
        ' * to find which pads are affected. Then assign motors/servos in S-pad order.',
        ' *',
        ' * timer_output_mode index = hardware timer number - 1.',
        ' * So timer_output_mode 0 = TIM1, timer_output_mode 7 = TIM8.',
        ' * All pads sharing a hardware timer get the same mode.',
        ' */',
        'export const INAV_TIMER_DATA: Record<string, InavTimerPin[]> = {',
    ]

    for board_name in sorted(boards.keys()):
        pins = boards[board_name]
        # Only include boards that have output pins
        output_pins = [p for p in pins if p['isOutput'] or p['isLed'] or p['isBeeper']]
        if not output_pins:
            continue

        lines.append(f'  {json.dumps(board_name)}: [')
        for pin in pins:
            pad = json.dumps(pin['padLabel'])
            lines.append(
                f'    {{ timerNum: {pin["timerNum"]}, padLabel: {pad}, '
                f'usage: {json.dumps(pin["usage"])}, '
                f'isOutput: {"true" if pin["isOutput"] else "false"}, '
                f'isLed: {"true" if pin["isLed"] else "false"}, '
                f'isBeeper: {"true" if pin["isBeeper"] else "false"} }},'
            )
        lines.append('  ],')

    lines.append('};')
    lines.append('')

    # Stats
    total_boards = len([b for b in boards if any(
        p['isOutput'] for p in boards[b])])
    total_pins = sum(
        len([p for p in boards[b] if p['padLabel']])
        for b in boards
    )

    lines.insert(7, f' * {total_boards} boards with output pins, {total_pins} total output pad mappings.')

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    return total_boards


def main():
    parser = argparse.ArgumentParser(
        description='Scrape INAV target.c files for timer-to-pad mappings')
    parser.add_argument('--inav-src', required=True,
                        help='Path to INAV src/main/target directory')
    parser.add_argument('--output', default='src/models/inavTimerData.ts',
                        help='Output TypeScript file path')
    args = parser.parse_args()

    target_dir = Path(args.inav_src)
    if not target_dir.is_dir():
        print(f'Error: {target_dir} is not a directory', file=sys.stderr)
        sys.exit(1)

    boards = {}
    skipped = 0

    for board_dir in sorted(target_dir.iterdir()):
        if not board_dir.is_dir():
            continue
        target_c = board_dir / 'target.c'
        if not target_c.exists():
            skipped += 1
            continue

        board_name = board_dir.name
        pins = parse_target_c(str(target_c))
        if pins:
            boards[board_name] = pins

    print(f'Parsed {len(boards)} boards ({skipped} skipped -- no target.c)')

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    total = generate_typescript(boards, str(output_path))

    print(f'Generated {output_path} with {total} boards')


if __name__ == '__main__':
    main()
